import type { Metadata } from "next";
import "../globals.css";
import Signature1 from "@/components/shared/Signature1";
import TopNavigation from "@/components/top/TopNavigation";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<>
			{/* <div className="fixed left-0 top-0 w-[70vw] h-screen z-[-50] pointer-events-none">
        <Image
          src="/6466e54c-d311-4a21-b303-c73b44c57a38.jpg"
          alt="Flower"
          fill
          className="object-contain"
          priority
        />
      </div> */}
			<Signature1 />
			<TopNavigation />
			{children}
		</>
	);
}
